In [34]:
def num (data):
    import numpy as np
    data = np.array(data)
    normalizedData =(data.transpose()-data.min(axis=1))/(data.max(axis=1)-data.min(axis=1))
    normalizedData=normalizedData.transpose()
    return normalizedData

In [35]:
data = [[25, -19, 35, 90, 73],[14.86452745, -26.8915466, -4.42219305, 6.3526264, 7.88297253],[0, 0, 1, 0, 1],[837, 302, 790, 271, 796],[49.97, 49.94, 51.37, 50.97, 51.29]]

In [36]:
print(num(data))

[[0.40366972 0.         0.49541284 1.         0.8440367 ]
 [1.         0.         0.53810982 0.79615179 0.83280145]
 [0.         0.         1.         0.         1.        ]
 [1.         0.05477032 0.91696113 0.         0.92756184]
 [0.02097902 0.         1.         0.72027972 0.94405594]]
